aws-os_lib-tmplt.c: fix pointer conversion issues under x86_64-pc-mingw32
With x86_64-pc-mingw32 sizeof(void *) != sizeof(long), this triggers the
following warnings / errors:

aws-os_lib-tmplt.c:342:11: warning: asm operand 1 probably doesn't match
constraints
  342 | /*NOGEN*/ CND(AI_ADDR_OFFSET, "???");
      |           ^~~
aws-os_lib-tmplt.c:323:11: error: impossible constraint in 'asm'
  323 | /*NOGEN*/ CND(SIN_FAMILY_OFFSET, "sin_family offset in record");
      |           ^~~
aws-os_lib-tmplt.c:340:11: error: impossible constraint in 'asm'
  340 | /*NOGEN*/ CND(AI_FAMILY_OFFSET, "???");
      |           ^~~
aws-os_lib-tmplt.c:341:11: error: impossible constraint in 'asm'
  341 | /*NOGEN*/ CND(AI_CANONNAME_OFFSET, "???");
      |           ^~~
aws-os_lib-tmplt.c:342:11: error: impossible constraint in 'asm'
  342 | /*NOGEN*/ CND(AI_ADDR_OFFSET, "???");
      |           ^~~

Let's use uintptr_t instead of long for the pointers.

TN: T125-001